image: node:16.14.0
pipelines:
  branches:
    develop:
      - step:
          name: "Build Staging/DEV"
          caches:
            - node
          script:
            - yarn
            - yarn build
          artifacts:
            - dist/**
      - step:
          name: "Deployment to Staging/DEV"
          script:
            - yarn global add firebase-tools
            - firebase deploy --token=1//09kxf5kdmMA4oCgYIARAAGAkSNwF-L9IraNCNUiQwj7-HgRd9T0hVVvb2xDm8IYrVWmgf_zHdEu512gApBZWQ5MvEwUk90_Iw9uA
      - step:
          name: "Build baldwin-ga/TEST"
          caches:
            - node
          script:
            - yarn
            - yarn ng build -c baldwin-ga
          artifacts:
            - dist/**
      - step:
          name: "Deployment to baldwin-ga/TEST"
          script:
            - yarn global add firebase-tools
            - firebase deploy --token=1//09kxf5kdmMA4oCgYIARAAGAkSNwF-L9IraNCNUiQwj7-HgRd9T0hVVvb2xDm8IYrVWmgf_zHdEu512gApBZWQ5MvEwUk90_Iw9uA
    master:
      - step:
          name: "Build Staging/PROD"
          caches:
            - node
          script:
            - yarn
            - yarn build --prod
          artifacts:
            - dist/**
      - step:
          name: "Deployment to Staging/DEV"
          script:
            - yarn global add firebase-tools
            - firebase deploy --token=1//09kxf5kdmMA4oCgYIARAAGAkSNwF-L9IraNCNUiQwj7-HgRd9T0hVVvb2xDm8IYrVWmgf_zHdEu512gApBZWQ5MvEwUk90_Iw9uA
    feature/baldwin-build:
      - step:
          name: "Build baldwin-ga/PROD"
          caches:
            - node
          script:
            - yarn
            - yarn ng build -c baldwin-ga
          artifacts:
            - dist/**
      - step:
          name: "Deployment to baldwin-ga/PROD"
          script:
            - yarn global add firebase-tools
            - firebase deploy --token=1//09kxf5kdmMA4oCgYIARAAGAkSNwF-L9IraNCNUiQwj7-HgRd9T0hVVvb2xDm8IYrVWmgf_zHdEu512gApBZWQ5MvEwUk90_Iw9uA

  default:  #This pipeline will run for every branch which is not defnied above
    - step:
        name: "Build Staging/DEV"
        caches:
          - node
        script:
          - yarn
          - yarn build
    - step:
        name: "Build Staging/PROD"
        caches:
          - node
        script:
          - yarn
          - yarn build --prod
